# -*- coding: utf-8 -*-
"""untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/alwinkaitharan/cd1157ea615c8a81cb548f0f76717fbd/untitled8.ipynb
"""

x=int(input("enter the number"))
for i in range(1,11):
  print(i,"*",x,"=",i*x)

num=int(input())
i=1
while(i<=10):
  print(i*num)
  i=i+1

x=input(" enter the number ")
d=0
for i in x:
  #print(i)
  d=d+1
print(d)

x=input("enter a name")
x=x.replace('a','k')
print(x)

string=input(("enter string: "))
reversestring= ""
for i in string:
    reversestring = i + reversestring
print("reverse string: ",reversestring)      
if (string == reversestring):
    print("the string is palindrome")
else:
    print("the string is not palindrome")

